### ISSUE TITLE
conflict with some websites

### ISSUE THREAD

**Issue by shuiliu11** [odebroqueville/contextSearch#115]
I can't click any hyperlinks when open https://www.taobao.com/ with only this add-on.
Firefox version: 95.0.2 (64-bit)

**Comment by odebroqueville** [comment]
Sorry to hear that but I can't reproduce the issue on Ffx 96! Do you mean that you cannot add a search engine for that website or that clicking on hyperlinks on that website doesn't work? I have difficulty helping you with this particular website because I don't read Chinese. All I can say is that, whenever I click on a link, it requires that I login. I don't have an account so I can't test further!

**Comment by shuiliu11** [comment]
"clicking on hyperlinks on that website doesn't work"

**Comment by odebroqueville** [comment]
I'm sorry but I can't reproduce the issue, so I can't debug any further! Please try re-installing the extension or you'll just have to disable the extension when visiting that website.
