### ISSUE TITLE
Console log

### ISSUE THREAD

**Issue by armandocin** [odebroqueville/contextSearch#128]
Hi,

first of all I love this add-on, thanks for your work.

I just want to report that after last update the application is logging in my console.
Being a developer I found this a little annoying. Hope you can fix soon.

Thanks again!

**Comment by odebroqueville** [comment]
Sorry about that! I forgot to change a variable setting for production. It's really annoying because I constantly have to toggle a variable setting on 3 scripts when I switch between debug and production mode. I wish their was a way around this! I'll do my best to turn console logging off for the next release. Closing the issue as this is something that I'm aware of. Thanks.

**Comment by GenericMale** [comment]
Guess you forgot to turn the console log off again for the 4.6.4 version.
