### ISSUE TITLE
Do Multi Search on all entries that just have the same Keyword?

### ISSUE THREAD

**Issue by Taurondir** [odebroqueville/contextSearch#142]
Maybe this is already possible and I can't read the manual correctly?
I was creating identical Keywords and trying to just launch Multi Search on the Keyword.

What I was trying to do is group multiple sets of entries together. For example, set 3 entries with Keyword "Pic" and 4 entries with Keyword "RealEstate" so that I can highlight a word and either do a Multi Search for and find Images for that keyword or just a Multi Search for real estate map addresses.

The way I understand now is that a Multi Search will use ALL the entries that have the little box between "Keyboard Shortcut" and "Search Engine URL"?

**Comment by odebroqueville** [comment]
Great idea!

Please give version 4.5.2 a try and tell me if it does what you needed and if you encounter any issues.

Cheers,
Olivier

On 29 Jun 2023, at 11:41, Taurondir ***@***.***> wrote:


Maybe this is already possible and I can't read the manual correctly?
I was creating identical Keywords and trying to just launch Multi Search on the Keyword.

What I was trying to do is group multiple sets of entries together. For example, set 3 entries with Keyword "Pic" and 4 entries with Keyword "RealEstate" so that I can highlight a word and either do a Multi Search for and find Images for that keyword or just a Multi Search for real estate map addresses.

The way I understand now is that a Multi Search will use ALL the entries that have the little box between "Keyboard Shortcut" and "Search Engine URL"?
