### ISSUE TITLE
Why is access to the clipboard required?

### ISSUE THREAD

**Issue by robsonsobral** [odebroqueville/contextSearch#150]
Hi! Thank you for the useful addon!

Just out of curiosity, why does the new version need access to the clipboard?

**Comment by odebroqueville** [comment]
Hi Sobral,

That’s a good question.

With this new release 4.6.0, users can now add AI prompts using the likes of ChatGPT, Google Bard and some others. The extension opens a new tab to one of these AI chatbots, but sadly it hasn’t always been possible to insert a prompt in textarea of the chatbot programmatically. Generating a click to submit AI requests automatically doesn’t seem possible either. I believe the AI providers are trying to discourage this kind of practice to favour the use of their APIs which aren’t free. The thing that they can’t prevent though, is users pasting stuff in the textarea from their clipboard. That would really hinder usability. That’s why I copy prompts to the clipboard so that users can easily paste the prompt in the textarea (if it’s missing) using CMD + V.

Hope this answers your question.

Btw, the extension only requires write access to the clipboard, not read access, so the extension has no idea of what’s on your clipboard.

Regards,
Olivier.


On 2 Aug 2023, at 19:22, Sobral ***@***.***> wrote:


Hi! Thank you for the useful addon!

Just out of curiosity, why does the new version need access to the clipboard?
