### ISSUE TITLE
Order of favicons in the grid of icons is different to the order of search engines in the Options page

### ISSUE THREAD

**Issue by Pachuquero** [odebroqueville/contextSearch#16]
This is a great extension. Unfortunately, the recent update changed a few things.

After the "silent" update the menu disappeared (I got it back by removing and re-clicking options). The shift + right click no longer works for access to favorites but the alt + right click does, though with a different ranking of the favorites from what appears under options. 

Also, the highlighted search term gets deselected once a single favorite has been clicked. I typically need to check several defined searches for an item, but now have to select the item again for each search, which means a fair bit of clicking.

Restarting the browser (FF) didn't change things...

**Comment by odebroqueville** [comment]
Shift-click has been replaced by Alt-click following user complaints. It's documented in the extensions description and on Github. I had to release version 3.71 in a rush because Firefox updates had broken things. Also, version 3.70 had a major bug. As a result, there still are some bugs around and I don't encourage using the reset button for the mean time. Have you tried multi-search? It gives you the option to carry out multiple searches with one click, but it works with the context menu not the grid of favicons, yet.

**Comment by Pachuquero** [comment]
Thanks for your response. I have more elements to multi-search than I normally want to to check, so I don't use that. Please don't forget that the highlighted search term gets unselected when one _favicon search_ has been done. It would be great to have at in the earlier version to reduce the amount of clicking.

**Comment by odebroqueville** [comment]
@Pachuquero I believe this issue has been fixed with release 3.8.0. Please test and let me know if I may close the issue. Thanks.

**Comment by Pachuquero** [comment]
Meanwhile, I've changed browser to Vivaldi and now use 'ContextSearch web-ext' which doesn't have the issue. Anyway, many thanks for your efforts!

**Comment by odebroqueville** [comment]
You're welcome. Thank you.
