### ISSUE TITLE
Context menu on website should pop up only when the text is selected

### ISSUE THREAD

**Issue by lamyergeier** [odebroqueville/contextSearch#167]
I have this settings

![image](https://github.com/odebroqueville/contextSearch/assets/42092626/fa240f8e-ea80-48a4-9741-1cc1b50fa517)

But it shows up even if the text is not selected:

![image](https://github.com/odebroqueville/contextSearch/assets/42092626/f296e830-0ce4-420e-b3f7-5d9baa13ce48)

**Comment by odebroqueville** [comment]
Would you please detail the steps you took right before the Icons Grid appeared?

**Comment by lamyergeier** [comment]
Select a text with mouse the pop menu appears. Make it disappear my moving in the mouse and then out of the pop up. Click anywhere without text the pop up appears again!

**Comment by odebroqueville** [comment]
I'm closing this issue as I haven't heard back from you since I posted a fix 5 days ago.

**Comment by lamyergeier** [comment]
@odebroqueville 

> Select a text with mouse the pop menu appears. Make it disappear my moving in the mouse and then out of the pop up. Click anywhere without text the pop up appears again!

Still facing this issue with the latest addon version

**Comment by odebroqueville** [comment]
@lamyergeier 
After you mouse in and out of the Icons Grid popup, the text remains selected, that's why the popup re-appears if you then click outside. Then, when you click on the page the popup appears and the text is unselected, so the popup won't re-appear. I could make changes to the code so the text gets unselected on a mouse out, but I think some users would prefer the text to remain selected. You can't please everyone! I also don't find that it's a big deal! Unfortunately, I couldn't find a keyboard shortcut to unselect text in Firefox!
