### ISSUE TITLE
Make the new tab active after it has finished loading completely

### ISSUE THREAD

**Issue by lamyergeier** [odebroqueville/contextSearch#171]
From Settings:

![image](https://github.com/odebroqueville/contextSearch/assets/42092626/f298d89d-31a6-4c73-a014-e2ca6fd18b51)

Is it possible to make the new tab active when it has finished loading completely?

**Comment by odebroqueville** [comment]
@lamyergeier 
That's what should happen if you checked the corresponding option as shown above. Is it not working for you?

**Comment by lamyergeier** [comment]
No, the tab becomes active immediately and it takes a few seconds for the website to load.

**Comment by odebroqueville** [comment]
Ah well I can't change that behaviour because[ it is set up that way in Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create). This is something that you might want to raise with the folks at Mozilla, more specifically at Bugzilla.

**Comment by lamyergeier** [comment]
May I suggest that you could add an option to specify after how many seconds the user would like to switch the focus to the new tab. May be I can set the value as 5 seconds, so that I am definitely sure  that in 5 seconds the page would have got loaded.

**Comment by odebroqueville** [comment]
@lamyergeier I don't think that this is feasible because all I'm doing is setting a property to "active: true" for a newly created tab. There is no option to delay when the property becomes active. I would have to resort to using something entirely different from browser.tabs.create, such as a fetch. That would involve rewriting a lot of code and complicate things substantially. This is not something that I have time for. However, I'm open to any other solution if you have one. Please read the documentation in the link that I provided to better understand what options I have.

**Comment by alan-2001** [comment]
So here's another example of "you can't please all the people all the time"! For the past week or so I've been a little bit annoyed by what seemed like a performance issue with this extension. And lo and behold, here is the explanation! For what it's worth, I prefer the way it used to jump to the new tab immediately, cos it showed me that it was doing something. But I'll get used to it, no problem. 

I'll take this opportunity to profusely thank odebroqueville for this extension. It is a mandatory addition to Firefox IMO and I use it countless times a day. So thanks very much; keep up the good work!

**Comment by odebroqueville** [comment]
@alan-2001 Thanks for your kind words, Alan. Although the new tab is only made active once the page has completed loading, you will know right away that it's doing something because the tab is created immediately. It just switches to the new tab later. If I find the time, I may add a setting to let users chose their preference for switching to a new tab, but it's not so much a priority right now because I'm focusing on bringing folders to CS. Cheers!

**Comment by alan-2001** [comment]
I wasn't going to come right out and _ask_ you to add that option, but if you do, it would be most appreciated! 

Thanks very much for the quick reply!
