### ISSUE TITLE
Add context menu item to download videos from YouTube or Vimeo

### ISSUE THREAD

**Issue by SchoepkeD** [odebroqueville/contextSearch#182]
Hi Olivier,

thank you for contextSearch! This thing has saved me boatloads of clicks :)

I have a little wish for a future version though:
So I filled the list of possible context search candidates manually, which works great: DuckDuck, Duden, Wiki, Wolfram, no problemo.
Once in a while though, I'd like to right-click on a link to some YT video and send that straight to YT Downloader's search mask. Unfortunately, contextSearch won't let me do that because in the link context of Firefox, contextSearch doesn't appear.

Would there be a possibility on your end to remedy that somehow?

All the Best, and thanks again,
Dieter

**Comment by odebroqueville** [comment]
Hi Dieter,

I don't quite understand what you're trying to do!

I understand that you'd like the Context Search menu to open when you right-click on a web link, but what would you like to happen thereafter? What is a YT Downloader search mask?

What information do you need to pass on to this YT Downloader search mask? Is it the web link (i.e. url address) you're right-clicking?

Thanks in advance for clarifying.
Cheers

**Comment by SchoepkeD** [comment]
Hi Olivier,
 
sorry for the confusion. The target website in question is this one:

https://www.yt1s.com/en2aef
 
This is probably the best Youtube-Downloader to date. You'll find the mask in the middle. For it to work, the link from the Youtube-Video / Youtube-Website is required. It has this shape:
 
https://www.youtube.com/watch?v=NWbPCuAzimw&pp=ygUGcGF6ZXJh

So, when I find something interesting in Youtube, I copy the link from there, start YT Downloader, paste the link, and wait for it to offer options.
I would like to save that step and, by help of contextSearch, transfer that link right into YTD's mask. Of course, it can't be a link anymore then, it has to be text.

Thanks for considering,
Dieter

**Comment by odebroqueville** [comment]
Hi @SchoepkeD , I've added the possibility to download videos from YouTube or Vimeo in version 5.0.6 but it requires some manual configurations. I've included an explanation to set up this feature in the extension's description page under the section 'Advanced features for macOS users'. Please have a look and let me know if you have any difficulties setting things up. On a side note, I'll shortly be releasing v5.0.7 which will make the nativeMessaging permission optional, so it will have to be enabled in Firefox to take advantage of video downloads.

**Comment by SchoepkeD** [comment]
Hello Olivier,


>>macOS users can download videos from YouTube or Vimeo by right-clicking on a video thumbnail
 
thankyou very much, but I use only Windows ;)
 
Best
Dieter


am Dienstag, 6. August 2024 um 12:18 schrieben Sie:

**Comment by odebroqueville** [comment]
Hi @SchoepkeD , it should work for Windows too but the configuration requirements are slightly different. I've added some instructions for Windows users in the extension's description and copied them below. Unfortunately, I can't test things cause I don't have a Windows machine. I'd be grateful if you could try it out.

## Advanced features for Windows users

### Install Python, ffmpeg and yt-dlp

Follow the instructions [here](https://chatgpt.com/share/56f68eed-b6c4-4454-9680-c82030e3737d)

### Download the yt_dlp_host files from the [Context Search repository on GitHub](https://github.com/odebroqueville/contextSearch)

Save the 3 files to a folder of your choosing

### Edit the yt_dlp_host.json file

Modify the 'path' property so that it points to the location of the yt_dlp_host.py file:

```
"path": "/path/to/yt_dlp_host.py",
```

### Edit the yt_dlp_host.bat file

Modify the path so that it points to the location of the yt_dlp_host.py file.

### Edit the yt_dlp_host.py file

Replace the line starting with result=subprocess.run() with:

```
result = subprocess.run(['yt-dlp', '--ffmpeg-location', '/path/to/ffmpeg', '-f', "(bv*[vcodec~='^((he|a)vc|h26[45])'][height>=720]+ba[ext=m4a]) / (bv*+ba/b)", '-P', '/path/to/Video Downloads', url], 
capture_output=True, 
text=True, 
check=True)
```

where /path/to/ffmpeg is the path to your ffmpeg binary and
where /path/to/Video Downloads is the path to the folder where you'd like to save your video downloads.

### Add Registry entries

The browser finds the extension based on registry keys which are located in a specific location. One of the two registry entries should be created for the messaging to work:

    HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\yt_dlp_host
    HKEY_LOCAL_MACHINE\Software\Mozilla\NativeMessagingHosts\yt_dlp_host

The default value for the key should be the path to the application manifest (yt_dlp_host.json).

Please refer to the [MDN web documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging#windows_setup) for instructions to configure native messaging for Windows.

Once you've completed the steps above, you should be all set. 

Please remember:

- for YouTube video downloads to work, you need to disable video previews in YouTube settings;
- nativeMessaging permission needs to be enabled in the extension's permission section.
