### ISSUE TITLE
Make nativeMessaging permission optional

### ISSUE THREAD

**Issue by rebmcr** [odebroqueville/contextSearch#184]
I am being asked to grant permission for "Exchange messages with programs other than Firefox" before Firefox can install this latest update to Context Search, which I do not see any reason for it to require. There does not appear to be anything populated under the Release Notes section.

Could you provide information about why this is being requested, and why I might want to allow it?

**Comment by deKambing** [comment]
Based on the changelog, it seems to be related to this new feature:

"Implemented feature request https://github.com/odebroqueville/contextSearch/issues/182: Added the option to download videos from YouTube or Vimeo"

 https://github.com/odebroqueville/contextSearch/blob/master/CHANGELOG.md

**Comment by odebroqueville** [comment]
@rebmcr Hi Ryan, it's a perfectly legitimate question. @Drtga3 is right, I've added the ability to download videos from YouTube or Vimeo. It requires the nativeMessaging permission to be enabled because Context Search has to communicate with a utility called yt-dlp (which has to be installed independently from CS). It does require some manual configuration, so I added an 'Advanced features' section in the extension's description explaining how to set this up for macOS users. I don't have a Windows system, so I'm afraid that Windows users will have to browse through the MDN web documentation to make it work. It's not too complicated, but for those who have never used a terminal before it might feel slightly daunting.

I will shortly release version 5.0.7 which will make the nativeMessaging permission optional so that users who aren't interested in video downloads don't have to accept it.
