### ISSUE TITLE
Unable to delete entries with spaces in their names

### ISSUE THREAD

**Issue by odie5533** [odebroqueville/contextSearch#26]
If I try to delete an entry with a space in its name, like "Stack Exchange" or "Google Maps", the entire list of search engines appears blank. When I refresh it they return, but the one I tried to delete is still there. If I rename it to "StackExchange" or "GoogleMaps" I can then delete it as normal.

**Comment by cjscheller** [comment]
I am able to consistently recreate this issue by continually removing search engines from the Options page at random with the trash can icon. This does not appear to be related to search engines with spaces in the name but instead appears to be caused by a race condition. 

`TypeError: divSearchEngines is null - options.js:528:19`

When `removeSearchEngine` executes, the removal of the search engine is persisted to the database. This eventually triggers two functions: `listSearchEngines` (thru handleStorageChange event listener) and `readData` (thru saveSearchEngines in function callback). The race condition occurs if `readData` attempts to access the **ol#searchEngines** element after it has been removed in `listSearchEngines` and before it has been reset.

It's possible this could also be causing #18, but I was not able to recreate that issue directly.
