### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by robsonsobral** [odebroqueville/contextSearch#29]
Hi!

Is really all these permissions necessary?

- Access your data for all websites
- Download files and read and modify the browser’s download history
- Display notifications to you
- Access browser tabs

I don't mean to accuse you. It's just pretty common for Android developers to forget about to check the necessary permissions and maybe the same happened here.

Thank you!

**Comment by odebroqueville** [comment]
I honestly don't understand why the first permission is required, but all others are necessary to provide the features the extension does provide:
- download/back up your list of search engines so that they can be uploaded again if something goes wrong
- display notification to give users insight as to what the extension is doing or when errors may be encountered
- access to browser tabs is required to open search results in a new tab or for the multisearch feature.

**Comment by LilDevil** [comment]
The "Access your data for all websites" shows up because the extension needs to inject it's content script onto all pages. The content script is to get the selection text that you want to search for.

**Comment by robsonsobral** [comment]
Thank you, everybody!
