### ISSUE TITLE
Not working in 52.4.0 ESR x64

### ISSUE THREAD

**Issue by AXTRACK** [odebroqueville/contextSearch#43]
I was trying to get google engine added in options and also by using the example .json but no luck. Seems like buttons in the options are not working except the browse one but nothing still added to the search engines after selecting the file.
Did play with older versions too but all the same. I am not getting the context menu entry as well but maybe that because no engines selected.
![2017-10-30_143432](https://user-images.githubusercontent.com/10299764/32170982-79ffa77c-bd7f-11e7-8a37-d089523e3235.png)

**Comment by odebroqueville** [comment]
This extension is really intended for firefox 56 and above. With versions 55 and below not all the features are available, e.g. favicons will not be displayed due to lack of support for all the features of webextensions. That said, the extension should still work in version 52 but requires setting the "webextensions.storage.sync.enabled" flag to "false" in about:config. Please give it a try and let me know how it goes.

**Comment by AXTRACK** [comment]
Thanks, that seems did the trick.
