### ISSUE TITLE
When releasing an extension update user's lose their custom list of search engines

### ISSUE THREAD

**Issue by odebroqueville** [odebroqueville/contextSearch#57]
This is a MAJOR BUG!

Whenever an extension update is released the list of search engines revert to the default list and users lose their custom list of search engines.

**Comment by odebroqueville** [comment]
@cjscheller Could you please look into this, Carl?

**Comment by cjscheller** [comment]
@odebroqueville Each time the extension is updated, background.js will run. Currently in background.js the **init()** function is being run, which resets the list of search engines to the default list. Therefore, every time the extension is updated (or "reloaded" in developer mode) the search engine list is reverted to default. 

By default, **init** should not reset to the default search engine list. Since this same function is triggered by the _Reset_ action, it could receive a parameter indicating what state to reset to. 

However, I think it makes more sense to completely decouple the **init** and **reset** functionalities into separate functions:
- **init** - initialize the extension and only set the search engines if they have not been previously set (for example, on first install)
- **reset** - to reset the extension to default settings and search engines only when triggered by the user

Let me know your thoughts and I can add a PR

**Comment by odebroqueville** [comment]
Hi Carl @cjscheller , there's something that I don't understand: if you look at the function initialiseSearchEngines(forceReload) in background.js line 299, you will see that: if searchEngines (fetched from storage.local) isn't empty and forceReload hasn't been set, then the default search engines are not loaded. Therefore, I don't see why the search engines would revert to default when updating the extension.

**Comment by cjscheller** [comment]
@odebroqueville Correct - forceReload is tied to the "forceSearchEnginesReload" option, which if set by the user will reset the default search engines on update and likely why it is happening to some users. My thought is that it should not be tied to this option (or any option), as this option indicates it is used only when reseting the extension. 

And yes, both updating and reloading the extension in developer mode have the same effect in terms of re-executing the extension's scripts.

**Comment by odebroqueville** [comment]
@cjscheller Do you think we should remove the option to force reload default search engines?

**Comment by cjscheller** [comment]
@odebroqueville Up to you, the option allows for flexibility when resetting so I don't see a major issue with it.

**Comment by odebroqueville** [comment]
@cjscheller maybe we should remove it as an option, i.e. checkbox, and instead replace it with a button 'Reset search engines to default list'. I understand this would prevent the force reload situation. What are your  thoughts?

**Comment by cjscheller** [comment]
@odebroqueville Again, up to you. I think it's a reasonable change. However, I also believe the force reload issue should now be fixed in the PR that I added, as it will no longer fire when updating the extension.
