### ISSUE TITLE
Add search engines ALREADY added through mycroft to the addon

### ISSUE THREAD

**Issue by rpgdev** [odebroqueville/contextSearch#67]
Like many I lost my context search addon because of quantum but I still have all my search engines I added from mycroft. Would be good if there was a way to add those engines into your addon too. Preferably by default. I prefer to add the mycroft engines anyways.

**Comment by odebroqueville** [comment]
I'm afraid I don't have any control over the way your search engines were stored with your previous add-on and one add-on can't talk to another add-on. You need to check with the author of your previous add-on if (s)he can create an export feature (preferably to a JSON file) so that your search engines can be imported in this add-on.

**Comment by rpgdev** [comment]
That's not a previous addon, it's the way firefox always did it: http://mycroftproject.com/ you went to this site and it stored the search engine in your list of search sites for firefox.

**Comment by odebroqueville** [comment]
If you're actually requesting to import your search engines from firefox, then your request is a duplicate of issue #60. https://github.com/odebroqueville/contextSearch/issues/60
