### ISSUE TITLE
Search Engines Reset

### ISSUE THREAD

**Issue by Ladergorn** [odebroqueville/contextSearch#69]
I have just discovered that my custom search engines have been lost and I am presented with a huge list of search engines - presumably the default list?
Likely to have happened on upgrade to 3.9.0
Thank you

**Comment by odebroqueville** [comment]
When was the last time you used Context Search before updating? You shouldn't have lost your custom search engines with release 3.9.0 or even 3.8.9. However, an update to release 3.8.7 may have caused the issue. We've been releasing quite a number of updates lately. Also, please always remember to export your custom list of search engines from the Options page so that you can re-import it if any thing goes wrong. I keep repeating myself, but it's always essential to make backups. If you continue to think that release 3.9.0 is faulty, then we really need to know what steps would help reproduce this bug.

**Comment by Ladergorn** [comment]
Hello and thanks for your reply. I will follow your suggestion for backups. 
I do have a recent full backup of my system. Are the custom search settings likely to be in there somewhere. Eg in the Firefox profile folder? 

⁣Get BlueMail for Android ​

**Comment by odebroqueville** [comment]
If you're on Mac, I'd use Time Machine to go back in time and export your custom list of search engines. Then you can come back to the latest point in time of your system and import the search engines from the Options page. If you're on Windows, I'd try to recover a firefox browser backup at least 6 days old. Then you can export, update your browser and import. The file in the browser is in SQLite format, so you'd have to copy-paste things.

**Comment by odebroqueville** [comment]
@Ladergorn Hello, have you been able to recover your custom search engines?
