### ISSUE TITLE
Implement caching to speed up the display of favicons

### ISSUE THREAD

**Issue by Smile4ever** [odebroqueville/contextSearch#71]
See #69 and https://github.com/mat/besticon/issues/31

**Comment by seanryan-seanryan** [comment]
Thanks for your responses. About the Cambridge Dictionary url: I definitely don’t want to go to the **spellchecker** – I’m aiming at the dictionary **definition (meaning)** pages. Go to site https://dictionary.cambridge.org/dictionary/english/ and type any word e.g. “test” in the search box and press enter. The response is e.g. https://dictionary.cambridge.org/dictionary/english/test. So https://dictionary.cambridge.org/dictionary/english/%s is an appropriate ContextSearch entry. Note that in ContextSearch Options, when I type in this url format and press click “Test Search Engine” – voila! – the correct page is loaded. If I use this ContextSearch entry on any page, it works too… except if you double-click the word (or drag highlight) so that the selected text (unintentionally) includes the trailing blank. You can prove this by going to any page that contains the word “test” and doing Context Search.
PS: I notice that the term must be all lowercase when building the url for Cambridge, but that’s not a matter for your extension. It’s just the trailing space that I’d hope to have stripped off the term as I think such behaviour would have universal value.
I'm not a developer, so hope you'll forgive my layman's perspective.

**Comment by odebroqueville** [comment]
Base64 strings will now be saved on first run and used to generate the context menu. The first build still takes time, but the subsequent builds are fine.
