### ISSUE TITLE
Scroll  to switch search engine

### ISSUE THREAD

**Issue by ghost** [odebroqueville/contextSearch#8]
is it possible to switch search engine by scroll mousewheel when hover on the right menu ? there was a uc.js script 
https://github.com/alice0775/userChrome.js/blob/master/ScrollSearchEngines_Fx48.0.uc.js

combine this addon that can do this  ff56-,but now ,uc.js was gone,can this addon add this feature?

**Comment by odebroqueville** [comment]
Thank you for this nice idea. I'm using the context menu from the webextensions API, so I'm not sure this can be implemented. But I like the idea, so I'll keep the request open.

**Comment by odebroqueville** [comment]
@cjscheller Hi Carl, I don't think this can be done. What are your thoughts on this?

**Comment by cjscheller** [comment]
@odebroqueville I believe that this is something that should be implemented separately from the extension, either by the browser itself or by a browser user script as the original poster indicated. Since this appears to be a rare request and the original poster has deleted their account, I'd say it makes sense to close this issue.
