### ISSUE TITLE
Storage quota exceeded

### ISSUE THREAD

**Issue by Sarkos** [odebroqueville/contextSearch#83]
I am unable to modify my preferences. Changes appear to take effect from the options UI, however it doesn't actually save, and in the console I can see an error message "Error: QuotaExceededError: storage.sync API call exceeded its quota limitations."

After turning off the option to save favicons, this error message stopped appearing, but every time I reopen the options UI it is reset to the default.

https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/

**Comment by odebroqueville** [comment]
Hi @Sarkos , thanks for bringing this up here.
Hi @cjscheller , the changes Mozilla have made to storage sync may explain the issues many users have been experiencing lately with the ffx 79 update. What puzzles me is that we purposefully migrated the search engines to local area storage and only kept the preferences in storage sync in order to stay with quota limitations, so I wonder where we went wrong!
The quota limitations for storage sync are as follows:
* Quota bytes: 102400
* Quota bytes per item: 8192
* Max items: 512
I don't see where we would be exceeding these quota limitations. It also doesn't make sense to me that favicons would be stored in storage sync.. they should be stored in storage local. Would you have some time to help me debug this issue?

**Comment by Sarkos** [comment]
I opened up the storage-sync.sqlite and it has 34 keys which are all quite large, here is an example:
{"id":"key-amazon","key":"amazon","data":{"index":0,"name":"Amazon.com (book search)","keyword":"a","url":"https://www.amazon.com/gp/search/ref=sr_adv_b/?search-alias=stripbooks&unfiltered=1&field-keywords=","show":true,"base64":"<snipped>"},"last_modified":1510737926204,"_status":"deleted"}

The base64 attribute which I left out was 23k characters long.

**Comment by odebroqueville** [comment]
@Sarkos Doesn't look to me that you're using the latest version of Context Search! I would suggest that you save/export your list of search engines and remove the extension. Restart your browser, then re-install the addon and import your search engines.

**Comment by Sarkos** [comment]
Strange, I see that now. It's on v3.72 and Firefox says there are no updates available.

![image](https://user-images.githubusercontent.com/2346625/91078456-eefcdb00-e642-11ea-972b-5f62bd63339e.png)

**Comment by odebroqueville** [comment]
Strange indeed! What is your OS?

**Comment by Sarkos** [comment]
Windows 10

I've just done as you suggested, reinstalled and imported my search engines and everything is working fine now, thanks!

**Comment by Sarkos** [comment]
I have a theory.... I notice that you changed your version number formatting after 3.72 to 3.8.0. I wonder if perhaps Firefox checks the version number and thinks that 72 > 8 therefore I'm on the latest version. There may be a lot of users stuck on old versions if this is the case. You could solve it by going up to major version 4.

**Comment by odebroqueville** [comment]
Nice tip! Many thanks.
