### ISSUE TITLE
Add-on no longer works on right mouse click

### ISSUE THREAD

**Issue by JoeHetro** [odebroqueville/contextSearch#86]
Add search engine to Context Search has recently appeared in address bar.  The right mouse button context search has disappeared.  Whether these two developments happened concurrently or the two events are coincidental (i.e. unrelated) I can't be sure.  What is clear is that the core functionality - the right click context search no longer works.

**Comment by odebroqueville** [comment]
"Add search engine to Context Search has recently appeared in address bar." >>> I don't understand this! Makes me wonder if you're not referring to another extension! We haven't provided that feature in Context Search! Otherwise, could be that your version is corrupt or that there is a compatibility issue with another extension. Have you tried removing and then re-installing the latest version of Context Search 4.0.0 ? (Don't forget to export your custom list of search engines before you re-install and import!)

**Comment by pvones** [comment]
See my issue #84

**Comment by JoeHetro** [comment]
Apologies, I wasn't notified of any comments until the thread was closed!  The issue is certainly with context search.  I have recorded the screen to demonstrate the issue: https://vimeo.com/user122411054/review/453625494/032153f5ff

**Comment by odebroqueville** [comment]
@JoeHetro your link is broken
