### ISSUE TITLE
Options are reset to default after re-starting Firefox

### ISSUE THREAD

**Issue by odebroqueville** [odebroqueville/contextSearch#92]
Steps to reproduce the issue:
1. Visit the extension's preferences page
2. Make some changes to the options, e.g. check the checkbox labled "Make the new tab or window active"
3. Close firefox
4. Re-open firefox and visit the extension's preferences page

Observed behavior: the checkbox will have reverted to the unchecked default.
Expected behavior: changes to options should be saved from one browser session to another. Therefore the options shouldn't be reset after re-starting the browser. The above checkbox should remain checked.

**Comment by cjscheller** [comment]
Tested commit and confirming that options maintain their customized state across: A) extension reinstall, and B) Firefox restart. 

However, I've also noticed that the search engine list is reset in both scenarios. Taking a look now.

**Comment by cjscheller** [comment]
After taking a deeper look, it seems that the search engines (stored in extension local storage) are **maintained** on restart of Firefox, but are **cleared** on extension reinstall (ie remove and then install extension). 

This is because Firefox is now clearing the local storage for an extension when it's been removed/uninstalled. This appears to be new functionality. 

If we are ok with the search engines being cleared when a user deliberately uninstalls the extension, then I think we can close this issue
